version: "3.7"

services:
  nginx_app:
    image: nginx:latest
    depends_on:
      - flask_app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
   
    

